# Generated by Django 4.1.7 on 2023-04-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=50, verbose_name=' სახელი გვარი')),
                ('phone_number', models.CharField(max_length=50, verbose_name=' ტელეფონის ნომერი')),
                ('town', models.CharField(max_length=50, verbose_name=' ქალაქი')),
                ('competitor', models.CharField(blank=True, choices=[('m', 'Magticom'), ('s', 'Silknet')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=50)),
                ('call_status', models.CharField(blank=True, choices=[('connected', 'Connected'), ('declined', 'Declined'), ('call me later', 'Call me later'), ("didn't answer", "Didn't answer the call")], max_length=50)),
                ('declined_reason', models.CharField(blank=True, choices=[('not interested', ' არ არის დაინტერესებული'), ('no internet', ' არ აქვს ინტერნეტი'), ('no device', ' არ აქვს Android/Smart TV'), ('too expensive', 'ძვირია')], max_length=50)),
                ('other_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='iptv_landing.application')),
                ('email', models.EmailField(max_length=254)),
                ('client_password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('town', models.CharField(choices=[('t', 'Tbilisi'), ('b', 'Batumi')], max_length=50)),
                ('hosts', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('first_payment_date', models.DateField(auto_now_add=True)),
                ('payed_until', models.DateField(null=True)),
                ('packets', models.CharField(choices=[('1', '1 Month'), ('3', '3 Month'), ('6', '6 Month')], max_length=50)),
                ('packet_plus', models.TextField(blank=True)),
                ('unsubscribe_reason', models.CharField(blank=True, choices=[('too expensive', 'Too expensive'), ("a lot of channels doesn't work", "A lot of channels doesn't work")], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iptv_landing.client')),
            ],
        ),
    ]
