# Generated by Django 4.1.7 on 2023-05-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationKZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=50, verbose_name=' Имя Фамилия')),
                ('phone_number', models.CharField(max_length=50, verbose_name=' Номер телефона')),
                ('town', models.CharField(max_length=50, verbose_name=' Город')),
                ('competitor', models.CharField(blank=True, choices=[('m', 'Magticom'), ('s', 'Silknet'), ('o', 'სხვა')], max_length=50, verbose_name=' Интернет провайдер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' Время получения заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=' Время изменения заявки')),
                ('application_status', models.CharField(choices=[('new', ' ახალი'), ('processed', ' მუშაობაში')], default='new', max_length=50, verbose_name=' Статус анкеты')),
                ('call_status', models.CharField(blank=True, choices=[('connected', ' ჩართულია'), ('declined', ' უარი თქვა'), ('call me later', ' მოგიანებით დამიკავშირდით'), ("didn't answer", ' არ მიპასუხა')], max_length=50, verbose_name=' Статус звонка')),
                ('declined_reason', models.CharField(blank=True, choices=[('not interested', ' არ არის დაინტერესებული'), ('no internet', ' არ აქვს ინტერნეტი'), ('no device', ' არ აქვს Android/Smart TV'), ('too expensive', 'ძვირია')], max_length=50, verbose_name=' Причина отказа')),
                ('other_comment', models.TextField(blank=True, verbose_name=' Доп. комментарий')),
            ],
            options={
                'verbose_name': ' Анкетка',
                'verbose_name_plural': ' Анкеты',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': ' ანკეტა', 'verbose_name_plural': ' ანკეტები'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': ' კლიენტი', 'verbose_name_plural': ' კლიენტები'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': ' გადახდა', 'verbose_name_plural': ' გადახდები'},
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('new', ' ახალი'), ('processed', ' მუშაობაში')], default='new', max_length=50, verbose_name=' ანკეტის სტატუსი'),
        ),
        migrations.AlterField(
            model_name='application',
            name='call_status',
            field=models.CharField(blank=True, choices=[('connected', ' ჩართულია'), ('declined', ' უარი თქვა'), ('call me later', ' მოგიანებით დამიკავშირდით'), ("didn't answer", ' არ მიპასუხა')], max_length=50, verbose_name=' ზარის სტატუსი'),
        ),
        migrations.AlterField(
            model_name='application',
            name='competitor',
            field=models.CharField(blank=True, choices=[('m', 'Magticom'), ('s', 'Silknet'), ('o', 'სხვა')], max_length=50, verbose_name=' პროვაიდერი'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' ანკეტის შემოსვლის დრო'),
        ),
        migrations.AlterField(
            model_name='application',
            name='declined_reason',
            field=models.CharField(blank=True, choices=[('not interested', ' არ არის დაინტერესებული'), ('no internet', ' არ აქვს ინტერნეტი'), ('no device', ' არ აქვს Android/Smart TV'), ('too expensive', 'ძვირია')], max_length=50, verbose_name=' უარის მიზეზი'),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_comment',
            field=models.TextField(blank=True, verbose_name=' დამატებითი კომენტარი'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name=' ცვლილება'),
        ),
        migrations.AlterField(
            model_name='client',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='iptv_landing.application', verbose_name=' ანკეტა'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_password',
            field=models.CharField(max_length=50, verbose_name=' პაროლი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, verbose_name=' კომენტარი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_payment_date',
            field=models.DateField(auto_now_add=True, verbose_name=' პირველი გადახდის თარიღი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='hosts',
            field=models.IntegerField(default=1, verbose_name=' მოწყობილობების რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='client',
            name='packet_plus',
            field=models.TextField(blank=True, verbose_name=' დამატები პაკეტი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='packets',
            field=models.CharField(choices=[('1', '1 თვე'), ('3', '3 თვე'), ('6', '6 თვე')], max_length=50, verbose_name=' პაკეტები'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payed_until',
            field=models.DateField(null=True, verbose_name=' მომდევნო გადახდა'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name=' ტელეფონის ნომერი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True, verbose_name=' სტატუსი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='town',
            field=models.CharField(max_length=50, verbose_name=' ქალაქი'),
        ),
        migrations.AlterField(
            model_name='client',
            name='unsubscribe_reason',
            field=models.CharField(blank=True, choices=[('too expensive', 'ძვირია'), ("a lot of channels doesn't work", 'ბევრი არხი არ მუშაობს'), ('rewind function ', 'გადახვევა არ მუშაობს'), ('freezes ', 'უჭედავს')], max_length=30, verbose_name=' გაუქმების მიზეზი'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(verbose_name=' თანხა'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iptv_landing.client', verbose_name=' კლიენტი'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_time',
            field=models.DateField(auto_now_add=True, verbose_name=' გადახდის თარიღი'),
        ),
        migrations.CreateModel(
            name='ClientKZ',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='iptv_landing.applicationkz', verbose_name=' Анкета')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client_password', models.CharField(max_length=50, verbose_name=' Пароль')),
                ('phone_number', models.CharField(max_length=50, verbose_name=' Номер телефона')),
                ('status', models.BooleanField(default=True, verbose_name=' Статус')),
                ('town', models.CharField(max_length=50, verbose_name=' Город')),
                ('hosts', models.IntegerField(default=1, verbose_name=' Кол-во устройств')),
                ('comment', models.TextField(blank=True, verbose_name=' Комментарий')),
                ('first_payment_date', models.DateField(auto_now_add=True, verbose_name=' Дата первого пополнения')),
                ('payed_until', models.DateField(null=True, verbose_name=' Дата следующей оплаты')),
                ('packets', models.CharField(choices=[('1', '1 თვე'), ('3', '3 თვე'), ('6', '6 თვე')], max_length=50, verbose_name=' Пакеты')),
                ('packet_plus', models.TextField(blank=True, verbose_name=' Доп. пакеты')),
                ('unsubscribe_reason', models.CharField(blank=True, choices=[('too expensive', 'ძვირია'), ("a lot of channels doesn't work", 'ბევრი არხი არ მუშაობს'), ('rewind function ', 'გადახვევა არ მუშაობს'), ('freezes ', 'უჭედავს')], max_length=30, verbose_name=' Причина отписки')),
            ],
            options={
                'verbose_name': ' Клиент',
                'verbose_name_plural': ' Клиенты',
            },
        ),
        migrations.CreateModel(
            name='PaymentsKZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateField(auto_now_add=True, verbose_name=' Дата оплаты')),
                ('amount', models.IntegerField(verbose_name=' Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iptv_landing.clientkz', verbose_name=' Клиент')),
            ],
            options={
                'verbose_name': ' Оплата',
                'verbose_name_plural': ' Оплаты',
            },
        ),
    ]
